### ISSUE TITLE
Error to open download file

### ISSUE THREAD

**Issue by apis3445** [dotnetcore/NPOI#75]
Hi! I try to read a excel file that was send by email. The version is 1.2.0
The code is
`using (var stream = new FileStream(fullPath, FileMode.Open, FileAccess.Read))
            {
                try
                {
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook  
                        headerRow = sheet.GetRow(0);
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook
                        headerRow = sheet.GetRow(0);

                    }
                }
                catch (EncryptedDocumentException e)
                {
                    // Checking of .xls file with password protected.
                    logger.LogError(e.Message);
                    return "Ocurrio un error al leer el archivo. El archivo puede estar protegido";
                }
                catch (Exception ex)
                {
                    logger.LogError(ex.Message);
                    return "Ocurrio un error al leer el archivo.";
                }
            `

and I get this exception: Invalid input data
`  at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.BodyRead(Byte[] buffer, Int32 offset, Int32 count)
   at NPOI.OpenXml4Net.Util.ZipInputStreamZipEntrySource.FakeZipEntry..ctor(ZipEntry entry, ZipInputStream inp)
   at NPOI.OpenXml4Net.Util.ZipInputStreamZipEntrySource..ctor(ZipInputStream inp)
   at NPOI.OpenXml4Net.OPC.ZipPackage..ctor(Stream filestream, PackageAccess access)
   at NPOI.OpenXml4Net.OPC.OPCPackage.Open(Stream in1)
   at NPOI.Util.PackageHelper.Open(Stream is1)
   at NPOI.XSSF.UserModel.XSSFWorkbook..ctor(Stream is1)
   at Caltic.Core.Gestion.IndicadorValores.<Importar>d__9.MoveNext() in D:\docs\0214net\Caltic\Caltic\Core\Gestion\IndicadorValores.cs:line 111`

If I save the excel again and I don't use the protected file I can read the file without errors

**Comment by Itoktsnhc** [comment]
@apis3445  
workaround:
add nuget package : SharpZipLib.NETStandard
this package will override the rc version package which npoi using now .
