### ISSUE TITLE
Create XSSFWorkbook error

### ISSUE THREAD

**Issue by Hugokk** [dotnetcore/NPOI#82]
In create XSSFWorkbook on error:

NPOI.POIXMLException
  HResult=0x80131500
  Message=
  Source=NPOI.OOXML
  StackTrace:
   at NPOI.XSSF.UserModel.XSSFWorkbook.newPackage()
   at NPOI.XSSF.UserModel.XSSFWorkbook..ctor()
   at Gerar.Excel.Program.Main(String[] args) in C:\Users\Desenvolvimento 03\source\repos\Gerar.Excel\Gerar.Excel\Program.cs:line 20

Inner Exception 1:
TypeInitializationException: The type initializer for 'NPOI.OpenXml4Net.OPC.OPCPackage' threw an exception.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. O sistema não pode encontrar o arquivo especificado.

**Comment by Kiwi15** [comment]
Same error. Any resolution ?

**Comment by SebZar** [comment]
Use SharpZipLib Version 1.0.0 for NPOI (Version 2.4.1).
The SharpZipLib Version 1.1.0 and 1.2.0 don't work for me.

Best regards
